# Generated by Django 5.1.4 on 2025-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('FRUIT', 'Fruits'), ('LEGUME', 'Légumes')], max_length=10)),
                ('saison', models.CharField(choices=[('PRINTEMPS', 'Printemps'), ('ETE', 'Été'), ('AUTOMNE', 'Automne'), ('HIVER', 'Hiver')], max_length=10)),
                ('cout_revient', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('prix_suggere', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
